name: settlement_sim
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  signalr_netcore: ^1.3.7
  flutter_lints: ^3.0.0
  flame: ^1.18.0
  http: ^1.2.1
  dio: ^5.9.2
  shared_preferences: ^2.2.2
  json_annotation: ^4.11.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  retrofit: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.14.1
  json_serializable: ^6.13.1
  retrofit_generator: ^10.2.5

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/ui/
    - assets/tiles/
    - assets/buildings/
    - assets/icons/
    - assets/npc/